#!/usr/bin/env python3
"""Fleet-specific vocabulary additions for HAV.

Generated by Oracle1 for the Cocapn Fleet.
These terms extend the base HAV with concepts unique to our architecture.
"""

from vocab import Term, Level

FLEET_TERMS = [
"A technician boards a malfunctioning habitat module's MUD to diagnose life support.", "The fleet commander boards the lead scout's session to assess a newly discovered structure."],
        bridges=
]

def register(hav):
    """Register fleet terms into an HAV instance."""
    from vocab import Namespace
    # Group by domain
    domains = {}
    for term in FLEET_TERMS:
        if term.domain not in domains:
            domains[term.domain] = Namespace(
                name=term.domain,
                description=f"Fleet-specific {term.domain} terms",
                terms={}
            )
        domains[term.domain].terms[term.name] = term

    for name, ns in domains.items():
        hav._namespaces[name] = ns

    return len(FLEET_TERMS)
